### PR TITLE
Support button

### PR DESCRIPTION
**Pull request by LaBoulange**
Support button configured to send 2 XTZ to tz1RZN17j7FuPtDpGpXKgMXbx57WEhpZGF6B, which is the address pointed by donate.awesome-tezos.tez.

Used the excellent https://tezos-share.stroep.nl/ to do that.

We had a stupidly hard time with the HTML, please feel free to squash if allowed! :-)

Linked checked.
Layout checked.

### CODE REVIEW

**Comment by skullzarmy** [comment]
I am not familiar with this service. I will do some due diligence before accepting this, but I appreciate your effort. 

It seems they take a fee (0.1xtz) from the txn, leading me to believe it goes through their Smart Contracts? Seems a bit overkill when sending XTZ wallet to wallet is so standardized already. 

Can you make any good arguments for the benefit?

**Comment by skullzarmy** [comment]
I cannot find any information about the organization or the smart contracts used. I don't feel like digging into the code. If you can provide some further information about the team behind this I will reconsider, but for now I think I will opt not to direct people to connect a wallet to this service. Thank you again for your suggestion, and please feel free to rebuff my argument if you feel it is in error.

**Comment by LaBoulange** [comment]
It's not really a service, but an experiment conducted by [@mknol](https://twitter.com/mknol) last year: https://twitter.com/AndreFvchs/status/1721228925886464164 - It was also discussed during a TC Twitter space a few days after that tweet.
In fact, the fee is more a donation than an actual fee (even though it's perceived, I meant in a philosophical standpoint), as we can see with various tools in the community.
We use it on our end, though this should not be taken as a sufficient argument: https://github.com/LaBoulange/tezos-baker

The rationale behind adding that button was the following;
* make the donation process easier, to encourage donations
* and do so by using a tool developped by a builder of the community (give the tool a life, somehow)

All this being said, it sure needs a DD, especially for a tool that manages XTZ transfers to a predefined recipient! I thought you knew the tool, sorry. I would have asked on Discord before posting otherwise.

**Comment by skullzarmy** [comment]
Please don't be sorry! Thank you for supporting your suggestion with some info. I will look into this more before making a final decision. I can always reopen the PR. Thank you again and please feel free to keep the suggestions coming!

**Pull request closed without merging**
