### PR TITLE
(readme.md): Added Tea to dev tools

### PR DESCRIPTION
**Pull request by LaBoulange**
Added Tea from alis.is to the development tools category

Link tested
Layout tested

### CODE REVIEW

**Comment by skullzarmy** [comment]
I wasn't aware of this. Seems really cool, but I am a bit concerned with the lack of recent dev. I wonder if this complies with the latest protocol. It seems the only two projects using it are abandoned as well. 

Do you know anything about the developers or use-cases of this personally? Have you successfully integrated this recently?

**Comment by LaBoulange** [comment]
Fair point!

Alis.is, the developper, is actually a member of Tez.Capital. They develop, among other things, TezPay and TazBake, formerly known as BakeBuddy.
I gave a try to Tea "just for fun" but some time ago, under Nairobi, to see hw it works. I don't have much time currently so I didn't retry under Oxford.

Would it make sense to invite Alis.is to that discussion, to make a decision based on what they say?

**Comment by skullzarmy** [comment]
I'm not against that. If I know the developer is interested in the project being added, that would certainly help assuage some concern.

**Comment by LaBoulange** [comment]
OK, I'm contacting them!

**Comment by cryi** [comment]
Hi @LaBoulange and @skullzarmy, the developer here.

The project is still actively maintained. Unlike projects such as Taqueria, which require frequent updates to stay in line with mainstream developments, our project serves as a template that evolves alongside your own projects. For example, in Starlords, we were among the first teams to implement the FA2.1 standard, all within the TEA environment.

Regarding the projects: BakeBuddy has been rebranded as [TzC](http://tez.capital) to reflect the expansion of our tools beyond just BakeBuddy. Meanwhile, Starlords has been temporarily put on hold, but it is certainly not abandoned.

To offer some reassurance, I've updated TEA to the latest version of Ligo and refreshed the references in the readme. 🙂

**Comment by skullzarmy** [comment]
@cryi thank you so much for stopping in and providing some insights on TEA. I look forward to diving into it myself!

**Pull request merged**
